### ISSUE TITLE
Card 06 - Research which API we should use for the trademark fetch

### ISSUE THREAD

**Issue by mknowlton89** [mknowlton89/trademark_search#11]
Also research what endpoints we'll need and what data we want back.

**Comment by mknowlton89** [comment]
We'll also want to make sure that what we get back is a JSON object & that we don't need an OAuth to use the API.

**Comment by eloy522752868** [comment]
We choose "https://uspto-trademark.p.rapidapi.com/v1/trademarkAvailable/
