### ISSUE TITLE
Card 08 - Get API keys for both of the API's needed for the project

### ISSUE THREAD

**Issue by mknowlton89** [mknowlton89/trademark_search#13]
The api key for the trademark fetch and the domain fetch (if needed).

**Comment by mknowlton89** [comment]
The API key for the domain API is: at_20p8HWePpxdOdgfSS2c42tVKGNMRB

**Comment by eloy522752868** [comment]
They have been added and have a variable they assigned to for we can easily change if code need to be changed.
