### ISSUE TITLE
Card 21 - Format the search query so that if it contains spaces, we can accurately check if the domain is available.

### ISSUE THREAD

**Issue by mknowlton89** [mknowlton89/trademark_search#32]
As a user, if I'm checking to see if "Yellow Potato" is trademarked, when I am redirected to results.html, the url parameter will be yellow%20potato - The browser indicates spaces with the "%20" string.

We will want to reformat that so that the %20 is removed.

We can use the following code: queryInputString = queryInput.replace(/%20/g, "");

**Comment by eloy522752868** [comment]
this has been added to result.js
