### ISSUE TITLE
Card 22 - Lookup which WHOIS API we should use

### ISSUE THREAD

**Issue by mknowlton89** [mknowlton89/trademark_search#33]
If a domain is not available, we want to call an API to get info about who owns the API (in case someone wants to contact the owner or buy it from them).

So we'll need the API to return who is the owner, at the least. But open to other cool/relevant info.

The API can't require an OAuth, and must return a response in JSON format.

**Comment by eloy522752868** [comment]
https://whois-history.whoisxmlapi.com/ but it is 12 bucks a month. I used https://api.hunter.io/v2/domain-search?domain. Not to happy with it but. it what we have free.
